import Layout from '@/components/Layout';
import Head from 'next/head';
import Image from 'next/image';
import prophetPhoto from '../../public/images/propetagaming.png';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image
                src={prophetPhoto}
                alt="Prophet Image"
                className="w-full h-auto"
              />
            </div>
            <div className="w-1/2">
              <h1>Hello, we are the Prohet Gaming.</h1>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation ullamco laboris
                nisi ut aliquip ex ea commodo consequat.
              </p>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
